openapi: 3.0.0 # version de OpenAPI utilisé
info: #ses infos évidemment 
  title: API Ping
  version: 1.0.0

paths:
  /ping: # méthode 
    get:
      summary: Vérifie la disponibilité de l'API
      responses:
        '200':
          description: Réponse OK avec "pong"
          content:
            text/plain:
              schema:
                type: string
                example: pong

