openapi: 3.0.3 
info: 
  title: API Ping
  version: 1.0.0
server: 
  - url: 'http://localhost:8080'

paths:
  /ping:  
    get:
      summary: Vérifie la disponibilité de l'API
      responses:
        '200':
          description: Réponse OK avec "pong"
          content:
            text/plain:
              schema:
                type: string
                example: pong

